In [115]:
import pandas as pd
import numpy as np

Tải dữ liệu xét tuyển đại học

In [116]:
df = pd.read_csv('dulieuxettuyendaihoc.csv', index_col="STT")
df.head(10)

,T1,L1,H1,S1,V1,X1,D1,N1,T2,L2,...,X6,D6,N6,GT,DT,KV,DH1,DH2,DH3,KT
STT,,,,,,,,,,,,,,,,,,,,,
1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,8.9,...,6.6,7.6,5.9,F,NaN,2NT,3.25,3.25,4.50,A1
2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,5.4,...,6.6,6.1,4.4,M,NaN,1,6.00,4.00,3.50,C
3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,4.9,...,7.9,8.1,4.6,M,NaN,1,5.00,6.75,4.00,C
4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,6.2,...,7.1,7.3,7.4,M,NaN,1,4.25,4.25,5.25,D1
5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,5.5,...,6.1,7.5,7.2,M,NaN,2NT,4.25,4.50,5.00,A
6,9.3,7.6,7.9,8.6,7.0,7.3,7.7,7.9,9.6,7.8,...,5.7,8.0,7.8,M,NaN,1,1.50,4.00,6.00,D1
7,2.8,3.9,5.5,6.9,5.0,7.3,4.6,5.2,4.4,6.7,...,6.6,6.0,6.0,F,NaN,2,6.50,6.75,5.25,C
8,8.3,6.0,7.6,5.1,7.5,4.7,5.8,7.2,6.7,6.3,...,7.1,6.8,7.0,F,NaN,2,3.75,4.50,4.25,D1
9,6.5,6.3,7.6,6.0,5.5,7.1,6.3,5.0,7.3,6.8,...,9.1,7.9,6.1,F,NaN,1,3.50,3.50,6.75,D1
10,7.3,5.9,4.7,7.1,6.7,7.9,6.7,7.7,8.0,6.8,...,6.4,6.1,7.8,F,NaN,1,4.00,4.75,5.50,D1

In [117]:
df.tail(10)

,T1,L1,H1,S1,V1,X1,D1,N1,T2,L2,...,X6,D6,N6,GT,DT,KV,DH1,DH2,DH3,KT
STT,,,,,,,,,,,,,,,,,,,,,
91,8.1,7.7,9.1,8.5,6.1,8.6,8.8,7.3,8.8,8.3,...,8.3,8.7,7.8,M,NaN,2,6.25,4.00,6.50,A
92,7.8,6.5,6.7,5.4,6.2,4.8,5.9,4.4,8.9,6.9,...,7.2,7.4,7.0,M,NaN,2NT,4.75,4.75,4.50,A
93,5.0,6.6,6.5,7.2,5.8,6.7,6.4,6.0,6.8,6.1,...,5.9,6.7,5.8,M,NaN,1,3.25,5.25,4.25,A
94,5.2,5.2,6.8,7.9,6.6,8.9,7.6,5.3,6.8,5.8,...,8.7,7.8,5.0,M,NaN,1,3.50,4.25,5.00,A
95,5.8,5.9,7.6,6.1,5.3,8.1,6.1,5.0,6.4,7.2,...,7.3,6.8,5.3,M,NaN,1,4.25,2.50,4.75,A
96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,6.8,...,6.3,6.1,6.2,F,NaN,1,5.25,1.50,6.25,C
97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,4.8,...,7.9,7.5,4.4,F,NaN,1,5.25,3.75,4.75,C
98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,7.3,...,9.6,8.4,5.8,M,NaN,2NT,7.00,8.00,4.00,C
99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,5.7,...,6.6,5.2,5.9,M,NaN,1,5.00,3.50,5.50,C
100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,6.4,...,5.6,6.6,5.8,M,NaN,2NT,5.25,2.50,4.25,C

In [118]:
# Thống kê dữ liệu thiếu cho cột dân tộc và hiệu chỉnh dữ liệu thiếu như sau: Mặc định thiếu  thì điền giá trị 0
df['DT'] = df['DT'].fillna(0)
df

,T1,L1,H1,S1,V1,X1,D1,N1,T2,L2,...,X6,D6,N6,GT,DT,KV,DH1,DH2,DH3,KT
STT,,,,,,,,,,,,,,,,,,,,,
1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,8.9,...,6.6,7.6,5.9,F,0.0,2NT,3.25,3.25,4.50,A1
2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,5.4,...,6.6,6.1,4.4,M,0.0,1,6.00,4.00,3.50,C
3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,4.9,...,7.9,8.1,4.6,M,0.0,1,5.00,6.75,4.00,C
4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,6.2,...,7.1,7.3,7.4,M,0.0,1,4.25,4.25,5.25,D1
5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,5.5,...,6.1,7.5,7.2,M,0.0,2NT,4.25,4.50,5.00,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,6.8,...,6.3,6.1,6.2,F,0.0,1,5.25,1.50,6.25,C
97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,4.8,...,7.9,7.5,4.4,F,0.0,1,5.25,3.75,4.75,C
98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,7.3,...,9.6,8.4,5.8,M,0.0,2NT,7.00,8.00,4.00,C
99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,5.7,...,6.6,5.2,5.9,M,0.0,1,5.00,3.50,5.50,C
100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,6.4,...,5.6,6.6,5.8,M,0.0,2NT,5.25,2.50,4.25,C

In [119]:
df['T1'] = df['T1'].fillna(df['T1'].mean())
df

,T1,L1,H1,S1,V1,X1,D1,N1,T2,L2,...,X6,D6,N6,GT,DT,KV,DH1,DH2,DH3,KT
STT,,,,,,,,,,,,,,,,,,,,,
1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,8.9,...,6.6,7.6,5.9,F,0.0,2NT,3.25,3.25,4.50,A1
2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,5.4,...,6.6,6.1,4.4,M,0.0,1,6.00,4.00,3.50,C
3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,4.9,...,7.9,8.1,4.6,M,0.0,1,5.00,6.75,4.00,C
4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,6.2,...,7.1,7.3,7.4,M,0.0,1,4.25,4.25,5.25,D1
5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,5.5,...,6.1,7.5,7.2,M,0.0,2NT,4.25,4.50,5.00,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,6.8,...,6.3,6.1,6.2,F,0.0,1,5.25,1.50,6.25,C
97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,4.8,...,7.9,7.5,4.4,F,0.0,1,5.25,3.75,4.75,C
98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,7.3,...,9.6,8.4,5.8,M,0.0,2NT,7.00,8.00,4.00,C
99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,5.7,...,6.6,5.2,5.9,M,0.0,1,5.00,3.50,5.50,C
100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,6.4,...,5.6,6.6,5.8,M,0.0,2NT,5.25,2.50,4.25,C

In [120]:
#6 Hãy thực hiện xử lý lần lượt tất cả dữ liệu thiếu cho các biến về điểm số còn lại
cot_diem = ['L1', 'H1', 'S1', 'V1', 'X1', 'D1', 'N1', 'T2', 'L2', 'H2', 'S2', 'V2', 'X2', 'D2', 'N2', 'L3', 'H3', 'S3', 'V3', 'X3', 'D3', 'N3', 'L4', 'H4', 'S4', 'V4', 'X4', 'D4', 'N4', 'L5', 'H5', 'S5', 'V5', 'X5', 'D5', 'N5', 'L6', 'H6', 'S6', 'V6', 'X6', 'D6', 'N6', 'DH1', 'DH2', 'DH3']
for col in cot_diem:
    df[col] = df[col].fillna(df[col].mean())
df

,T1,L1,H1,S1,V1,X1,D1,N1,T2,L2,...,X6,D6,N6,GT,DT,KV,DH1,DH2,DH3,KT
STT,,,,,,,,,,,,,,,,,,,,,
1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,8.9,...,6.6,7.6,5.9,F,0.0,2NT,3.25,3.25,4.50,A1
2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,5.4,...,6.6,6.1,4.4,M,0.0,1,6.00,4.00,3.50,C
3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,4.9,...,7.9,8.1,4.6,M,0.0,1,5.00,6.75,4.00,C
4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,6.2,...,7.1,7.3,7.4,M,0.0,1,4.25,4.25,5.25,D1
5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,5.5,...,6.1,7.5,7.2,M,0.0,2NT,4.25,4.50,5.00,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,6.8,...,6.3,6.1,6.2,F,0.0,1,5.25,1.50,6.25,C
97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,4.8,...,7.9,7.5,4.4,F,0.0,1,5.25,3.75,4.75,C
98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,7.3,...,9.6,8.4,5.8,M,0.0,2NT,7.00,8.00,4.00,C
99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,5.7,...,6.6,5.2,5.9,M,0.0,1,5.00,3.50,5.50,C
100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,6.4,...,5.6,6.6,5.8,M,0.0,2NT,5.25,2.50,4.25,C

In [121]:
#7.Tạo các biến TBM1, TBM2, TBM3 tương ứng với trung bình môn của các năm lớp 10, 11 và 12.
for i, suffix in enumerate(['1', '2', '6'], 1):
    df[f'TBM{i}'] = (df[f'T{suffix}']*2 + df[f'L{suffix}'] + df[f'H{suffix}'] +
                     df[f'S{suffix}'] + df[f'V{suffix}']*2 + df[f'X{suffix}'] +
                     df[f'D{suffix}'] + df[f'N{suffix}']) / 10
print(df[['TBM1', 'TBM2', 'TBM3']].head())

     TBM1  TBM2  TBM3
STT
1    7.00  7.54  7.01
2    4.69  5.47  5.07
3    5.77  5.38  6.04
4    6.21  5.20  6.88
5    6.50  6.36  6.99

In [122]:

#8. Tạo các biến xếp loại XL1, XL2 và XL3 dựa trên TBM1,TBM2 và TBM3 cho từng năm lớp 10, 11, 12 như sau:
#• Nhỏ hơn 5.0 xếp loại: yếu (kí hiệu là Y)
#• Từ 5.0 đến dưới 6.5: trung bình (kí hiệu là TB)
#• Từ 6.5 đến dưới 8.0: khá (kí hiệu là K)
#• Từ 8.0 đến dưới 9.0: giỏi (kí hiệu là G)
#• Từ 9.0 trở lên: xuất sắc (kí hiệu là XS)
def xl(tbm):
    if tbm < 5.0:
        return 'Y'
    elif 5.0 <= tbm < 6.5:
        return 'TB'
    elif 6.5 <= tbm < 8.0:
        return 'K'
    elif 8.0 <= tbm < 9.0:
        return 'G'
    else:
        return 'XS'
df['XL1'] = df['TBM1'].apply(xl)
df['XL2'] = df['TBM2'].apply(xl)
df['XL3'] = df['TBM3'].apply(xl)
df[['TBM1', 'XL1', 'TBM2', 'XL2','TBM3', 'XL3', ]]

     TBM1 XL1  TBM2 XL2  TBM3 XL3
STT
1    7.00   K  7.54   K  7.01   K
2    4.69   Y  5.47  TB  5.07  TB
3    5.77  TB  5.38  TB  6.04  TB
4    6.21  TB  5.20  TB  6.88   K
5    6.50   K  6.36  TB  6.99   K
..    ...  ..   ...  ..   ...  ..
96   7.43   K  7.42   K  6.83   K
97   4.93   Y  5.15  TB  6.39  TB
98   7.05   K  7.84   K  7.67   K
99   4.15   Y  4.72   Y  5.29  TB
100  5.26  TB  5.72  TB  5.85  TB

[100 rows x 6 columns]

In [123]:
#9. Tạo các biến US_TBM1, US_TBM2 và US_TBM3 để chuyển điểm trung bình các năm lớp
# 10, 11 và 12 từ thang điểm 10 của Việt Nam sang thang điểm 4 của Mỹ. Sử dụng phương
# pháp Min-Max Normalization
df['US_TBM1'] = (df['TBM1'] / 10) * 4
df['US_TBM2'] = (df['TBM2'] / 10) * 4
df['US_TBM3'] = (df['TBM3'] / 10) * 4

df[['TBM1', 'US_TBM1', 'TBM2', 'US_TBM2', 'TBM3', 'US_TBM3']].head()

     TBM1  US_TBM1  TBM2  US_TBM2  TBM3  US_TBM3
STT
1    7.00    2.800  7.54    3.016  7.01    2.804
2    4.69    1.876  5.47    2.188  5.07    2.028
3    5.77    2.308  5.38    2.152  6.04    2.416
4    6.21    2.484  5.20    2.080  6.88    2.752
5    6.50    2.600  6.36    2.544  6.99    2.796

In [124]:
#10. Tạo biến kết quả xét tuyển (kí hiệu là KQXT) nhằm xác định sinh viên đậu (giá trị “1”) và
# rớt ( giá trị “0”) vào các khối dựa trên điểm DH1, DH2 và DH3 như sau
def xet_tuyen(row):
    kt = row['KT']
    dh1 = row['DH1']
    dh2 = row['DH2']
    dh3 = row['DH3']

    if kt in ['A', 'A1']:
        score = (dh1*2 + dh2 + dh3) / 4
    elif kt == 'B':
        score = (dh1 + dh2*2 + dh3) / 4
    else:
        score = (dh1 + dh2 + dh3) / 3

    return 1 if score >= 5.0 else 0
df['KQXT'] = df.apply(xet_tuyen, axis=1)
df[['KT', 'DH1', 'DH2', 'DH3', 'KQXT']].head()

     KT   DH1   DH2   DH3  KQXT
STT
1    A1  3.25  3.25  4.50     0
2     C  6.00  4.00  3.50     0
3     C  5.00  6.75  4.00     1
4    D1  4.25  4.25  5.25     0
5     A  4.25  4.50  5.00     0

In [125]:
# 11.  Lưu trữ dữ liệu xuống ổ đĩa thành file processed_dulieuxettuyendaihoc.csv
df.to_csv('processed_dulieuxettuyendaihoc.csv', index=False)